name: Build Google Play AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Generate Android Skeleton
        run: |
          rm -rf android
          flutter create . --project-name=allfree_language_app --org=com.waiyan --platforms=android

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze & Validate Code
        run: flutter analyze || true

      - name: Build Play Store App Bundle
        run: flutter build appbundle --release --no-tree-shake-icons

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-bundle
          path: build/app/outputs/bundle/release/app-release.aab

